//! Namespace-aware Note lifecycle commands. Preparation only edits private
//! Yrs documents; persistence and GUI publication use the body-edit gateway.
use super::*;
use crate::namespace::{Entry, Namespace};
use crate::persistence::PersistedDocument;
use yrs::{
    Doc, MapPrelim, Text, WriteTxn, Xml, XmlElementPrelim, XmlFragment, XmlOut, XmlTextPrelim,
};

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct NoteRequest {
    #[schemars(range(min = 1, max = 1))]
    pub schema_version: u32,
    pub workspace_id: String,
    /// Copy identity from source.replica_id. Required while synchronization is enabled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub replica_id: Option<String>,
    /// source.workspace_metadata_revision from a current tree/read response.
    #[schemars(range(min = 1, max = 9_007_199_254_740_991_i64))]
    pub expected_workspace_revision: i64,
    pub request_id: String,
    pub action: NoteAction,
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Placement {
    First,
    Last,
    Before { entry_id: String },
    After { entry_id: String },
}

#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "op", rename_all = "snake_case", deny_unknown_fields)]
pub enum NoteAction {
    /// Create a Note and its one Namespace placement. IDs are generated by Core.
    Create {
        title: String,
        parent_entry_id: Option<String>,
        placement: Placement,
        /// Optional initial body, with the same subset as append_markdown. No headings.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        markdown: Option<String>,
    },
    /// Change only the Root title and title cache, preserving all document IDs.
    Rename {
        note_id: String,
        #[schemars(range(min = 1, max = 9_007_199_254_740_991_i64))]
        expected_revision: i64,
        title: String,
    },
    /// Move an existing Note/group placement with its descendants, not its content.
    Move {
        entry_id: String,
        parent_entry_id: Option<String>,
        placement: Placement,
    },
}
impl NoteAction {
    pub fn note_id(&self) -> Option<&str> {
        match self {
            Self::Rename { note_id, .. } => Some(note_id),
            _ => None,
        }
    }
}
impl NoteRequest {
    pub fn validate(&self) -> Result<(), ReadError> {
        if let Some(id) = &self.replica_id {
            validate_id(id)?;
        }
        validate_id(&self.workspace_id)?;
        if self.schema_version != 1
            || !(1..=9_007_199_254_740_991).contains(&self.expected_workspace_revision)
            || serde_json::to_vec(self)?.len() > MAX_INPUT_BYTES
        {
            return Err(invalid(
                "Unsupported schema, invalid Workspace revision, or input over 1 MiB",
            ));
        }
        let id = uuid::Uuid::parse_str(&self.request_id)
            .map_err(|_| invalid("request_id must be UUIDv4/v7"))?;
        if !matches!(id.get_version_num(), 4 | 7) || id.to_string() != self.request_id {
            return Err(invalid("request_id must be canonical lowercase UUIDv4/v7"));
        }
        match &self.action {
            NoteAction::Create {
                title,
                parent_entry_id,
                placement,
                ..
            } => {
                validate_title(title)?;
                validate_placement(parent_entry_id, placement)?;
            }
            NoteAction::Rename {
                note_id,
                expected_revision,
                title,
            } => {
                validate_id(note_id)?;
                validate_title(title)?;
                if !(1..=9_007_199_254_740_991).contains(expected_revision) {
                    return Err(invalid("Invalid Note revision"));
                }
            }
            NoteAction::Move {
                entry_id,
                parent_entry_id,
                placement,
            } => {
                validate_id(entry_id)?;
                validate_placement(parent_entry_id, placement)?;
            }
        }
        Ok(())
    }
}
pub(super) fn validate_title(title: &str) -> Result<(), ReadError> {
    if title.len() > 4096 || title.contains(['\r', '\n', '\0']) {
        Err(invalid(
            "title must be a single line of at most 4096 UTF-8 bytes",
        ))
    } else {
        Ok(())
    }
}
fn validate_placement(parent: &Option<String>, placement: &Placement) -> Result<(), ReadError> {
    if let Some(id) = parent {
        validate_id(id)?;
    }
    if let Placement::Before { entry_id } | Placement::After { entry_id } = placement {
        validate_id(entry_id)?;
    }
    Ok(())
}
fn live_entry<'a>(namespace: &'a Namespace, id: &str) -> Result<&'a Entry, ReadError> {
    namespace
        .entries
        .get(id)
        .filter(|entry| entry.deleted_at.is_none())
        .ok_or_else(|| ReadError::new("INVALID_TARGET", "Live Namespace entry not found"))
}
fn entry_map<T: ReadTxn>(
    txn: &T,
    entries: &yrs::MapRef,
    id: &str,
) -> Result<yrs::MapRef, ReadError> {
    match entries.get(txn, id) {
        Some(yrs::Out::YMap(value)) => Ok(value),
        _ => Err(invalid("Namespace entry is missing")),
    }
}

pub(super) fn prepare(workspace: &Path, request: NoteRequest) -> Result<PreparedEdit, ReadError> {
    request.validate()?;
    let reader = WorkspaceReader::open(workspace)?;
    require_edit_schema(&reader)?;
    if reader.workspace_id != request.workspace_id {
        return Err(ReadError::new(
            "WORKSPACE_MISMATCH",
            "Workspace identity does not match",
        ));
    }
    let agent = AgentRequest::from(request.clone());
    let fingerprint = agent.fingerprint()?;
    if let Some(result) = receipt(&reader.connection, agent.clone())? {
        return Ok(PreparedEdit {
            request: agent,
            fingerprint,
            documents: vec![],
            result,
            workspace_revision: reader.workspace_revision,
            replayed: true,
        });
    }
    if request.expected_workspace_revision != reader.workspace_revision {
        return Err(ReadError::new("WORKSPACE_CHANGED", "Read the current tree again and reconsider the requested placement")
            .with_details(json!({"expected_revision":request.expected_workspace_revision,"current_revision":reader.workspace_revision})));
    }
    let stored = load_document(&reader.connection, "workspace", &reader.workspace_id)?;
    let normalized = stored.schema_version == crate::replicated_namespace::SCHEMA_VERSION;
    let doc = if normalized {
        crate::replicated_namespace::legacy_projection(&stored)?
    } else {
        decode_document(&stored)?
    };
    let vector = doc.transact().state_vector();
    let now = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true);
    let mut documents = vec![];
    let mut changed = true;
    let mut result = json!({"schema_version":1,"ok":true,"request_id":request.request_id,"revision_scope":"workspace",
        "revision_before":reader.workspace_revision,"workspace_revision_before":reader.workspace_revision,"replayed":false,
        "changed_block_ids":[],"created_block_ids":[],"diff_truncated":false,"validated_edits":1});
    {
        let mut txn = doc.transact_mut();
        let root = txn
            .get_map("workspace")
            .ok_or_else(|| invalid("Missing Workspace"))?;
        let Some(yrs::Out::YMap(notes)) = root.get(&txn, "notes") else {
            return Err(invalid("Missing Note metadata"));
        };
        let Some(yrs::Out::YMap(namespace)) = root.get(&txn, "main_namespace") else {
            return Err(invalid("Missing Namespace"));
        };
        let Some(yrs::Out::YMap(entries)) = namespace.get(&txn, "entries") else {
            return Err(invalid("Missing Namespace entries"));
        };
        match &request.action {
            NoteAction::Create {
                title,
                parent_entry_id,
                placement,
                markdown,
            } => {
                let blocks = match markdown {
                    Some(markdown) => markdown::parse(markdown, &reader)?,
                    None => vec![
                        json!({"type":"paragraph","attrs":{"blockId":uuid::Uuid::now_v7().to_string()},"content":[]}),
                    ],
                };
                let (position, repaired) = place(
                    &reader.namespace,
                    None,
                    parent_entry_id.as_deref(),
                    placement,
                    &request.request_id,
                )?;
                let note_id = uuid::Uuid::now_v7().to_string();
                let entry_id = uuid::Uuid::now_v7().to_string();
                let note = new_note(&note_id, title, &blocks, &now)?;
                let meta = notes.insert(&mut txn, note_id.as_str(), MapPrelim::default());
                meta.insert(&mut txn, "title_cache", title.as_str());
                meta.insert(&mut txn, "created_at", now.as_str());
                meta.insert(&mut txn, "updated_at", now.as_str());
                meta.insert(&mut txn, "deleted_at", yrs::Any::Null);
                meta.insert(&mut txn, "trash_operation_id", yrs::Any::Null);
                let entry = entries.insert(&mut txn, entry_id.as_str(), MapPrelim::default());
                entry.insert(
                    &mut txn,
                    "parent_entry_id",
                    parent_entry_id.clone().map_or(yrs::Any::Null, Into::into),
                );
                entry.insert(&mut txn, "position", position.as_str());
                entry.insert(
                    &mut txn,
                    "target",
                    yrs::Any::from_json(&json!({"kind":"note","id":note_id}).to_string()).unwrap(),
                );
                entry.insert(&mut txn, "created_at", now.as_str());
                entry.insert(&mut txn, "updated_at", now.as_str());
                entry.insert(&mut txn, "deleted_at", yrs::Any::Null);
                entry.insert(&mut txn, "trash_operation_id", yrs::Any::Null);
                repair_positions(&mut txn, &entries, &repaired)?;
                let mut snapshot = note
                    .transact()
                    .encode_state_as_update_v1(&StateVector::default());
                let mut created = PersistedDocument {
                    kind: "note".into(),
                    document_id: note_id.clone(),
                    schema_version: 6,
                    revision: 1,
                    snapshot_revision: 1,
                    snapshot: snapshot.clone(),
                    updates: vec![],
                };
                if normalized {
                    snapshot = crate::replicated_note::edit::migrate(
                        &created,
                        &local_replica_id(&reader)?,
                    )?;
                    created.snapshot = snapshot.clone();
                    created.schema_version = crate::replicated_note::SCHEMA_VERSION;
                }
                let parsed = read_note(&created, false)?;
                let mut created_ids = vec![];
                collect_ids(&blocks, &mut created_ids);
                result["created_block_ids"] = json!(created_ids);
                result["note_id"] = note_id.clone().into();
                result["entry_id"] = entry_id.into();
                result["changes"] = json!([{"operation":"create","title":title,"parent_entry_id":parent_entry_id,"placement":placement,
                    "markdown":crate::markdown_read::section_markdown(&parsed.root, 0, &reader.workspace_id)}]);
                result["reindexed_entry_ids"] = json!(repaired.keys().collect::<Vec<_>>());
                documents.push(DocumentCommitInput {
                    kind: "note".into(),
                    document_id: note_id,
                    schema_version: created.schema_version,
                    base_revision: 0,
                    snapshot: Some(snapshot),
                    update: None,
                });
            }
            NoteAction::Rename {
                note_id,
                expected_revision,
                title,
            } => {
                live_note(&reader, note_id)?;
                let stored = load_document(&reader.connection, "note", note_id)?;
                if ![6, 7].contains(&stored.schema_version) {
                    return Err(ReadError::new(
                        "MIGRATION_REQUIRED",
                        "Open the Note in the updated GUI first",
                    ));
                }
                check_revision(*expected_revision, stored.revision)?;
                let before = read_note(&stored, false)?;
                changed = before.root.title != *title;
                result["revision_scope"] = "note".into();
                result["revision_before"] = stored.revision.into();
                result["note_id"] = note_id.clone().into();
                result["changes"] = if changed {
                    json!([{"operation":"rename","section_id":note_id,"before":before.root.title,"after":title}])
                } else {
                    json!([])
                };
                if changed {
                    let note = editable_note_document(&stored)?;
                    let vector = note.transact().state_vector();
                    rename_title(&note, title, &now)?;
                    let meta = entry_map(&txn, &notes, note_id)?;
                    meta.insert(&mut txn, "title_cache", title.as_str());
                    meta.insert(&mut txn, "updated_at", now.as_str());
                    documents.push(DocumentCommitInput {
                        kind: "note".into(),
                        document_id: note_id.clone(),
                        schema_version: stored.schema_version,
                        base_revision: stored.revision,
                        snapshot: None,
                        update: Some(edited_note_update(&stored, &note, &vector, &reader, &now)?),
                    });
                }
            }
            NoteAction::Move {
                entry_id,
                parent_entry_id,
                placement,
            } => {
                let entry = live_entry(&reader.namespace, entry_id)?;
                if let Some(target) = &entry.target {
                    live_note(&reader, &target.id)?;
                }
                let (position, repaired) = place(
                    &reader.namespace,
                    Some(entry_id),
                    parent_entry_id.as_deref(),
                    placement,
                    &request.request_id,
                )?;
                changed = entry.parent_entry_id != *parent_entry_id
                    || entry.position != position
                    || !repaired.is_empty();
                result["entry_id"] = entry_id.clone().into();
                result["note_id"] = json!(entry.target.as_ref().map(|target| &target.id));
                result["changes"] = if changed {
                    json!([{"operation":"move","entry_id":entry_id,"before_parent_entry_id":entry.parent_entry_id,
                    "before_position":entry.position,"after_parent_entry_id":parent_entry_id,"after_position":position,"placement":placement}])
                } else {
                    json!([])
                };
                result["reindexed_entry_ids"] = json!(repaired.keys().collect::<Vec<_>>());
                if changed {
                    let entry = entry_map(&txn, &entries, entry_id)?;
                    entry.insert(
                        &mut txn,
                        "parent_entry_id",
                        parent_entry_id.clone().map_or(yrs::Any::Null, Into::into),
                    );
                    entry.insert(&mut txn, "position", position.as_str());
                    entry.insert(&mut txn, "updated_at", now.as_str());
                    repair_positions(&mut txn, &entries, &repaired)?;
                }
            }
        }
    }
    if changed {
        let snapshot = doc
            .transact()
            .encode_state_as_update_v1(&StateVector::default());
        let desired = crate::namespace::read_namespace(&PersistedDocument {
            snapshot,
            schema_version: if normalized { 3 } else { stored.schema_version },
            updates: vec![],
            snapshot_revision: stored.revision,
            ..stored.clone()
        })?;
        let update = if normalized {
            crate::replicated_namespace::reconcile(&stored, &desired, &local_replica_id(&reader)?)?
        } else {
            doc.transact().encode_state_as_update_v1(&vector)
        };
        documents.push(DocumentCommitInput {
            kind: "workspace".into(),
            document_id: reader.workspace_id,
            schema_version: stored.schema_version,
            base_revision: stored.revision,
            snapshot: None,
            update: Some(update),
        });
    }
    result["revision_after"] =
        (result["revision_before"].as_i64().unwrap() + i64::from(changed)).into();
    result["workspace_revision_after"] = (reader.workspace_revision + i64::from(changed)).into();
    result["applied_edits"] = i64::from(changed).into();
    result["status"] = if changed { "applied" } else { "no_change" }.into();
    if serde_json::to_vec(&result["changes"])?.len() > MAX_DIFF_BYTES {
        result["changes"] = json!([]);
        result["diff_truncated"] = true.into();
    }
    if serde_json::to_vec(&result)?.len() > MAX_RESULT_BYTES {
        return Err(invalid("Edit result is too large"));
    }
    Ok(PreparedEdit {
        request: agent,
        fingerprint,
        documents,
        result,
        workspace_revision: reader.workspace_revision,
        replayed: false,
    })
}

fn repair_positions(
    txn: &mut yrs::TransactionMut,
    entries: &yrs::MapRef,
    positions: &BTreeMap<String, String>,
) -> Result<(), ReadError> {
    for (id, position) in positions {
        entry_map(txn, entries, id)?.insert(txn, "position", position.as_str());
    }
    Ok(())
}

fn place(
    namespace: &Namespace,
    moving: Option<&str>,
    parent: Option<&str>,
    placement: &Placement,
    seed: &str,
) -> Result<(String, BTreeMap<String, String>), ReadError> {
    let mut cursor = parent;
    while let Some(id) = cursor {
        if Some(id) == moving {
            return Err(ReadError::new(
                "INVALID_TARGET",
                "Cannot move an entry below itself or a descendant",
            ));
        }
        cursor = live_entry(namespace, id)?.parent_entry_id.as_deref();
    }
    let mut siblings = namespace
        .entries
        .values()
        .filter(|e| e.deleted_at.is_none() && e.parent_entry_id.as_deref() == parent)
        .collect::<Vec<_>>();
    siblings.sort_by(|a, b| (&a.position, &a.entry_id).cmp(&(&b.position, &b.entry_id)));
    let old_index = siblings
        .iter()
        .position(|e| Some(e.entry_id.as_str()) == moving);
    siblings.retain(|e| Some(e.entry_id.as_str()) != moving);
    let index =
        match placement {
            Placement::First => 0,
            Placement::Last => siblings.len(),
            Placement::Before { entry_id } | Placement::After { entry_id } => siblings
                .iter()
                .position(|e| &e.entry_id == entry_id)
                .ok_or_else(|| {
                    ReadError::new(
                        "INVALID_TARGET",
                        "Placement anchor must be a different live sibling of the target parent",
                    )
                })?
                + usize::from(matches!(placement, Placement::After { .. })),
        };
    if old_index == Some(index) {
        return Ok((
            namespace.entries[moving.unwrap()].position.clone(),
            BTreeMap::new(),
        ));
    }
    let lower = index.checked_sub(1).map(|i| siblings[i].position.as_str());
    let upper = siblings.get(index).map(|e| e.position.as_str());
    let mut repaired = BTreeMap::new();
    let position = if lower.is_some() && lower == upper {
        let key = lower.unwrap();
        let first = siblings.iter().position(|e| e.position == key).unwrap();
        let end = siblings.iter().rposition(|e| e.position == key).unwrap() + 1;
        if end - first > 1000 {
            return Err(ReadError::new(
                "LIMIT_EXCEEDED",
                "Too many colliding sibling positions to repair in one request",
            ));
        }
        let mut low = first.checked_sub(1).map(|i| siblings[i].position.clone());
        let high = siblings.get(end).map(|e| e.position.as_str());
        let mut selected = String::new();
        for slot in first..=end {
            let key =
                crate::sibling_position::between(low.as_deref(), high, &format!("{seed}:{slot}"))?;
            if slot == index {
                selected = key.clone();
            } else {
                let i = if slot > index { slot - 1 } else { slot };
                repaired.insert(siblings[i].entry_id.clone(), key.clone());
            }
            low = Some(key);
        }
        selected
    } else {
        crate::sibling_position::between(lower, upper, seed)?
    };
    Ok((position, repaired))
}

fn new_note(id: &str, title: &str, blocks: &[Value], now: &str) -> Result<Doc, ReadError> {
    let doc = Doc::new();
    {
        let mut txn = doc.transact_mut();
        let meta = txn.get_or_insert_map("meta");
        meta.insert(&mut txn, "note_id", id);
        meta.insert(&mut txn, "schema_version", 6);
        meta.insert(&mut txn, "created_at", now);
        meta.insert(&mut txn, "updated_at", now);
        let fragment = txn.get_or_insert_xml_fragment("body");
        let root = fragment.push_back(&mut txn, XmlElementPrelim::empty("section"));
        let header = root.push_back(&mut txn, XmlElementPrelim::empty("sectionHeader"));
        header.insert_attribute(&mut txn, "sectionId", id);
        header.insert_attribute(&mut txn, "tags", "[]");
        header.push_back(&mut txn, XmlTextPrelim::new(title));
        let body = root.push_back(&mut txn, XmlElementPrelim::empty("sectionBody"));
        let chunk = body.push_back(&mut txn, XmlElementPrelim::empty("bodyChunk"));
        chunk.insert_attribute(&mut txn, "chunkId", uuid::Uuid::now_v7().to_string());
        for (i, block) in blocks.iter().enumerate() {
            projection::insert_block(&mut txn, &chunk, i as u32, block)?;
        }
        projection::split_chunks(&mut txn, &body)?;
        root.push_back(&mut txn, XmlElementPrelim::empty("sectionChildren"));
    }
    Ok(doc)
}
fn rename_title(doc: &Doc, title: &str, now: &str) -> Result<(), ReadError> {
    let mut txn = doc.transact_mut();
    let fragment = txn
        .get_xml_fragment("body")
        .ok_or_else(|| invalid("Missing Note body"))?;
    let Some(XmlOut::Element(section)) = fragment.get(&txn, 0) else {
        return Err(invalid("Missing Root Section"));
    };
    let Some(XmlOut::Element(header)) = section.get(&txn, 0) else {
        return Err(invalid("Missing Root header"));
    };
    let nodes = header.children(&txn).collect::<Vec<_>>();
    let mut first = true;
    for node in nodes {
        let XmlOut::Text(text) = node else {
            return Err(invalid("Title is not text"));
        };
        let len = text.len(&txn);
        text.remove_range(&mut txn, 0, len);
        if first {
            text.insert(&mut txn, 0, title);
            first = false;
        }
    }
    if first {
        header.push_back(&mut txn, XmlTextPrelim::new(title));
    }
    txn.get_map("meta")
        .ok_or_else(|| invalid("Missing Note metadata"))?
        .insert(&mut txn, "updated_at", now);
    Ok(())
}
fn collect_ids(blocks: &[Value], output: &mut Vec<String>) {
    for block in blocks {
        if let Some(id) = block["attrs"]["blockId"].as_str() {
            output.push(id.into());
        }
        if let Some(children) = block["content"].as_array() {
            collect_ids(children, output);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn placement_repairs_only_the_colliding_bucket_and_preserves_display_order() {
        let mut ns = Namespace {
            namespace_id: "unused".into(),
            entries: BTreeMap::new(),
            notes: BTreeMap::new(),
        };
        for (id, position) in [
            ("a", "Zz"),
            ("b", "a0"),
            ("c", "a0"),
            ("d", "a0"),
            ("e", "a1"),
        ] {
            ns.entries.insert(
                id.into(),
                Entry {
                    entry_id: id.into(),
                    parent_entry_id: None,
                    position: position.into(),
                    target: None,
                    name: Some(id.into()),
                    created_at: "unused".into(),
                    updated_at: "unused".into(),
                    deleted_at: None,
                    trash_operation_id: None,
                },
            );
        }
        let (position, repaired) = place(
            &ns,
            None,
            None,
            &Placement::Before {
                entry_id: "c".into(),
            },
            "seed",
        )
        .unwrap();
        assert_eq!(repaired.len(), 3);
        assert!(!repaired.contains_key("a"));
        assert!(!repaired.contains_key("e"));
        let keys = [
            "Zz",
            &repaired["b"],
            &position,
            &repaired["c"],
            &repaired["d"],
            "a1",
        ];
        assert!(keys.windows(2).all(|pair| pair[0] < pair[1]));
        assert!(keys.iter().all(|key| crate::namespace::valid_position(key)));
        // This placement already has the requested display order; do not
        // rebalance its colliding bucket for an otherwise no-op command.
        let (key, unchanged) = place(
            &ns,
            Some("c"),
            None,
            &Placement::Before {
                entry_id: "d".into(),
            },
            "seed",
        )
        .unwrap();
        assert_eq!(key, "a0");
        assert!(unchanged.is_empty());
        assert!(
            place(
                &ns,
                Some("a"),
                None,
                &Placement::After {
                    entry_id: "a".into()
                },
                "seed"
            )
            .is_err()
        );
        ns.entries.get_mut("b").unwrap().parent_entry_id = Some("a".into());
        assert!(
            place(
                &ns,
                None,
                None,
                &Placement::Before {
                    entry_id: "b".into()
                },
                "seed"
            )
            .is_err()
        );
        assert!(place(&ns, Some("a"), Some("b"), &Placement::Last, "seed").is_err());
        // Group movement is the same placement operation, with no NoteDoc.
        assert!(place(&ns, Some("b"), None, &Placement::Last, "seed").is_ok());
    }
}
